title: "Machine Learning Project: Uber Fare Price Predictor"
description: Team: Ari Nair, Leo Alexeyev, Suhas Kumar, Sanjay Vijayasekar, Adil Shaik
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman